name: PR

on: pull_request

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: read

jobs:
  lint-markdown:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Lint markdown
        uses: docker://ghcr.io/ponylang/shared-docker-ci-markdownlint:20260810

  check-spelling:
    name: Spellcheck markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v6.0.2
      - name: Check spelling
        # streetsidesoftware/cspell-action v8.2.0
        uses: streetsidesoftware/cspell-action@d5d910b521ad408f1e7383c24609079f5a88bdca
        with:
          use_cspell_files: true
          incremental_files_only: false
